run:
  timeout: 5m
  go: '1.22'
  modules-download-mode: readonly

output:
  sort-results: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - durationcheck
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - interfacebloat
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - stylecheck
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  gocognit:
    min-complexity: 20

  lll:
    line-length: 120

  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - return

  misspell:
    locale: US

  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers
          - sayRepetitiveInsteadOfStutters

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gosec
        - dupl
        - lll
    - path: cmd/
      linters:
        - gochecknoinits
    - linters:
        - lll
      source: "^//go:generate "